version: '3'

services:
  service1:
    container_name: "service-1"
    image: nginx
    # ports:
    #   - 8081:80
    volumes:
      - ./service-1/:/usr/share/nginx/html:ro
  service2:
    container_name: "service-2"
    image: nginx
    # ports:
    #   - 8082:80
    volumes:
      - ./service-2/:/usr/share/nginx/html:ro
  proxy:
    container_name: "reverse-proxy"
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./static/:/usr/share/nginx/html:ro
      - ./conf.d:/etc/nginx/conf.d:ro
  my-server:
    container_name: "my-server"
    build: ./server
    ports:
      - 8083:80