version: '3'

services:
  service1:
    container_name: "service-1"
    image: nginx
    volumes:
      - ~/Sandbox/nginx-docker/service-1/:/usr/share/nginx/html:ro
  service2:
    container_name: "service-2"
    image: nginx
    volumes:
      - ~/Sandbox/nginx-docker/service-2/:/usr/share/nginx/html:ro
  proxy:
    container_name: "reverse-proxy"
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ~/Sandbox/nginx-docker/static/:/usr/share/nginx/html:ro
      - ~/Sandbox/nginx-docker/conf.d:/etc/nginx/conf.d:ro
  my-server:
    container_name: "my-server"
    image: my-server
    ports:
      - 8083:80